replicaCount: 3
image:
  repository: quay.io/wire/proxy
  tag: 2.77.0
service:
  externalPort: 8080
  internalPort: 8080
resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"
config:
  logLevel: Debug
# NOTE: Without an empty dictionary, you will see warnings
#       when overriding envVars
envVars: {}
